FROM python:3.11-slim

WORKDIR /app

COPY requirements_fastapi.txt .

RUN pip install --no-cache-dir -r requirements_fastapi.txt

COPY . .

CMD ["uvicorn", "payment_module.app:app", "--host", "0.0.0.0", "--port", "8000"]